### ISSUE TITLE
Python doesn't find MagickWand

### ISSUE THREAD

**Issue by DaniloTnk** [benschweizer/python-magickwand#2]
Hi, I'm configuring a RedHat 6.6, in my code I use MagickWand.

I've already installed ImageMagick by yum and the devel packs but when I try to run my code the following error apears:

```
Traceback (most recent call last):
  File "/data/www/los-back/logenerator_services/services/main.py", line 9, in <module>
    from file import file_upload_services
  File "/data/www/los-back/logenerator_services/services/file/file_upload_services.py", line 12, in <module>
    from wand.image import Image
  File "/data/env/lib/python2.7/site-packages/wand/image.py", line 20, in <module>
    from .api import MagickPixelPacket, libc, libmagick, library
  File "/data/env/lib/python2.7/site-packages/wand/api.py", line 1278, in <module>
    traceback.format_exc())
ImportError: MagickWand shared library not found or incompatible
Original exception was raised in:
Traceback (most recent call last):
  File "/data/env/lib/python2.7/site-packages/wand/api.py", line 739, in <module>
    ctypes.c_void_p] # PixelWand color
  File "/opt/rh/python27/root/usr/lib64/python2.7/ctypes/__init__.py", line 373, in __getattr__
    func = self.__getitem__(name)
  File "/opt/rh/python27/root/usr/lib64/python2.7/ctypes/__init__.py", line 378, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib64/libMagickWand.so.2: undefined symbol: DrawSetBorderColor
```

Result for yum install ImageMagick:

```
Loaded plugins: product-id, rhnplugin, security, subscription-manager
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Install Process
Package ImageMagick-6.5.4.7-7.el6_5.x86_64 already installed and latest version
Nothing to do
```

And for pip install MagickWand:

```
/<path_to_project>/env/bin/pip install MagickWand
Requirement already satisfied (use --upgrade to upgrade): MagickWand in /data/env/lib/python2.7/site-packages
```

**Comment by benschweizer** [comment]
Hi, I'm on travel, but from the stack trace, it looks like you have an old
magickwand lib installed (.2.so) and some required c symbols are not there.
Look if there's also graphicsmagick or another version and try that.
Otherwise, you could comment our the error trlhriwing functions

Greetings
Benjamin
Am 04.09.2015 3:16 nachm. schrieb "Danilo Tanaka" <notifications@github.com

**Comment by DaniloTnk** [comment]
Hi, sorry for the delay to answer.
It was holiday and I just check my e-mail today.
I'll  check the version of the lib, because I up the same requirements in
other computer and it work fine.
Thank you very much for your time.

Thankful,
Danilo Tanaka

2015-09-05 13:01 GMT-03:00 Benjamin Schweizer notifications@github.com:
